import Foundation
@testable import MLXCoderCore
import Testing

@Suite
struct SwiftFeatureRuntimeTests {
    @Test
    func processRunnerWritesStandardInput() async throws {
        let result = try await AsyncProcessRunner.run(
            executableURL: URL(fileURLWithPath: "/bin/cat"),
            arguments: [],
            stdinData: Data("hello feature\n".utf8),
            timeout: 10
        )

        #expect(result.exitCode == 0)
        #expect(result.stdout == "hello feature\n")
    }

    @Test
    func registryDiscoversExecutableManifest() throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-registry-\(UUID().uuidString)", isDirectory: true)
        let featureURL = rootURL.appendingPathComponent("example", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }

        try FileManager.default.createDirectory(
            at: featureURL,
            withIntermediateDirectories: true
        )
        let executableURL = featureURL.appendingPathComponent("feature")
        try "#!/bin/sh\n".write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )
        try """
        {
          "id": "example",
          "enabled": true,
          "executable": "feature",
          "tools": [
            {
              "name": "feature.example.echo",
              "description": "Echo test",
              "inputSchema": {
                "type": "object",
                "properties": {
                  "text": { "type": "string" }
                },
                "required": ["text"]
              }
            }
          ]
        }
        """.write(
            to: featureURL.appendingPathComponent(SwiftFeatureRegistry.manifestFilename),
            atomically: true,
            encoding: .utf8
        )

        let bundles = SwiftFeatureRegistry.discoverFeatureBundles(
            searchRoots: [rootURL]
        )

        #expect(bundles.count == 1)
        #expect(bundles.first?.id == "example")
        #expect(bundles.first?.tools.first?.name == "feature.example.echo")
        #expect(bundles.first?.tools.first?.inputSchema.contains(#""required":["text"]"#) == true)
    }

    @Test
    func registrySupportsGeneratedFeaturePackageManifestSchema() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-schema-\(UUID().uuidString)", isDirectory: true)
        let featureURL = rootURL.appendingPathComponent("rich", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }

        try FileManager.default.createDirectory(
            at: featureURL,
            withIntermediateDirectories: true
        )
        let executableURL = featureURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        if [ "$1" = "--list-tools" ]; then
          printf '{"tools":[{"name":"custom.dynamic","description":"Dynamic custom tool","inputSchema":"{}"}]}\\n'
          exit 0
        fi
        cat >/dev/null
        printf '{"ok":true,"output":"custom-output"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )
        try """
        {
          "schemaVersion": 1,
          "id": "custom-feature",
          "displayName": "Custom Feature",
          "description": "Feature generated by an agent.",
          "enabled": true,
          "executable": "feature",
          "discoversToolsAtRuntime": true,
          "toolNamePrefixes": ["custom."],
          "toolNameAliases": ["CustomDynamic"],
          "build": {
            "system": "swiftpm",
            "packagePath": ".",
            "product": "custom-feature",
            "configuration": "release",
            "executablePath": ".build/release/custom-feature"
          },
          "generated": {
            "by": "mlx-coder",
            "prompt": "Need a custom feature",
            "createdAt": "2026-05-30T12:00:00Z"
          },
          "tools": []
        }
        """.write(
            to: featureURL.appendingPathComponent(SwiftFeatureRegistry.manifestFilename),
            atomically: true,
            encoding: .utf8
        )

        let bundles = SwiftFeatureRegistry.discoverFeatureBundles(
            searchRoots: [rootURL]
        )
        #expect(bundles.first?.id == "custom-feature")
        #expect(bundles.first?.toolNamePrefixes == ["custom."])
        #expect(bundles.first?.toolNameAliases == ["CustomDynamic"])
        #expect(bundles.first?.discoversToolsAtRuntime == true)

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])
        let statuses = await runtime.featureStatuses()
        #expect(statuses.first?.displayName == "Custom Feature")
        #expect(statuses.first?.description == "Feature generated by an agent.")
        #expect(statuses.first?.build?.product == "custom-feature")
        #expect(statuses.first?.generated?.by == "mlx-coder")

        let descriptors = await runtime.descriptors(
            allowedToolNames: ["custom."]
        )
        #expect(descriptors.map(\.name) == ["custom.dynamic"])
    }

    @Test
    func featureScaffoldCreatesSwift63PackageBuildsAndEnables() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-scaffold-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])
        let scaffoldOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-scaffold",
                name: "feature.scaffold",
                argumentsObject: [
                    "id": "example-feature",
                    "toolName": "example.echo"
                ],
                argumentsJSON: #"{"id":"example-feature","toolName":"example.echo"}"#
            )
        )
        let scaffold = try JSONDecoder().decode(
            SwiftFeatureScaffoldReport.self,
            from: Data(scaffoldOutput.utf8)
        )

        let packageFirstLine = try String(
            contentsOf: URL(fileURLWithPath: scaffold.packagePath),
            encoding: .utf8
        ).components(separatedBy: .newlines).first
        #expect(packageFirstLine == "// swift-tools-version: 6.3")

        let validateOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-validate",
                name: "feature.validate",
                argumentsObject: ["id": "example-feature"],
                argumentsJSON: #"{"id":"example-feature"}"#
            )
        )
        let validation = try JSONDecoder().decode(
            SwiftFeatureValidationReport.self,
            from: Data(validateOutput.utf8)
        )
        #expect(validation.ok)

        let buildOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-build",
                name: "feature.build",
                argumentsObject: ["id": "example-feature"],
                argumentsJSON: #"{"id":"example-feature"}"#
            )
        )
        let build = try JSONDecoder().decode(
            SwiftFeatureBuildReport.self,
            from: Data(buildOutput.utf8)
        )
        #expect(build.ok)
        #expect(FileManager.default.isExecutableFile(atPath: build.executablePath))

        _ = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-enable",
                name: "feature.enable",
                argumentsObject: ["id": "example-feature"],
                argumentsJSON: #"{"id":"example-feature"}"#
            )
        )

        let descriptors = await runtime.descriptors(
            allowedToolNames: [SwiftFeatureRuntime.generatedFeatureToolsAllowedName]
        )
        #expect(descriptors.map(\.name).contains("example.echo"))

        let output = try await runtime.executeIfAvailable(
            toolCall: DirectAgentToolCall(
                id: "example-echo",
                name: "example.echo",
                argumentsObject: ["text": "ciao"],
                argumentsJSON: #"{"text":"ciao"}"#
            ),
            workingDirectory: rootURL
        )
        #expect(output == "ciao")
    }

    @Test
    func featureInstallCopiesBuildsAndEnablesExternalFeature() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-install-root-\(UUID().uuidString)", isDirectory: true)
        let sourceURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-install-source-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
            try? FileManager.default.removeItem(at: sourceURL)
        }

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])
        _ = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-install-scaffold",
                name: "feature.scaffold",
                argumentsObject: [
                    "id": "install-feature",
                    "toolName": "installed.echo",
                    "path": sourceURL.path
                ],
                argumentsJSON: "{}"
            )
        )

        let installOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-install",
                name: "feature.install",
                argumentsObject: [
                    "path": sourceURL.path
                ],
                argumentsJSON: "{}"
            )
        )
        let install = try JSONDecoder().decode(
            SwiftFeatureInstallReport.self,
            from: Data(installOutput.utf8)
        )

        #expect(install.ok)
        #expect(install.copied)
        #expect(install.built)
        #expect(install.enabled)
        #expect(install.destinationPath == rootURL.appendingPathComponent("install-feature").path)
        #expect(FileManager.default.fileExists(atPath: install.manifestPath))

        let descriptors = await runtime.descriptors(
            allowedToolNames: [SwiftFeatureRuntime.generatedFeatureToolsAllowedName]
        )
        #expect(descriptors.contains { $0.name == "installed.echo" })

        let output = try await runtime.executeIfAvailable(
            toolCall: DirectAgentToolCall(
                id: "feature-install-invoke",
                name: "installed.echo",
                argumentsObject: ["text": "installato"],
                argumentsJSON: #"{"text":"installato"}"#
            ),
            workingDirectory: rootURL
        )
        #expect(output == "installato")
    }

    @Test
    func featureValidateRejectsNonSwift63Package() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-swift-version-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])
        let scaffoldOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-scaffold",
                name: "feature.scaffold",
                argumentsObject: [
                    "id": "wrong-version-feature",
                    "toolName": "wrongversion.echo"
                ],
                argumentsJSON: #"{"id":"wrong-version-feature","toolName":"wrongversion.echo"}"#
            )
        )
        let scaffold = try JSONDecoder().decode(
            SwiftFeatureScaffoldReport.self,
            from: Data(scaffoldOutput.utf8)
        )
        var packageContents = try String(
            contentsOf: URL(fileURLWithPath: scaffold.packagePath),
            encoding: .utf8
        )
        packageContents = packageContents.replacingOccurrences(
            of: "// swift-tools-version: 6.3",
            with: "// swift-tools-version: 6.2"
        )
        try packageContents.write(
            to: URL(fileURLWithPath: scaffold.packagePath),
            atomically: true,
            encoding: .utf8
        )

        let validateOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-validate",
                name: "feature.validate",
                argumentsObject: ["id": "wrong-version-feature"],
                argumentsJSON: #"{"id":"wrong-version-feature"}"#
            )
        )
        let validation = try JSONDecoder().decode(
            SwiftFeatureValidationReport.self,
            from: Data(validateOutput.utf8)
        )

        #expect(!validation.ok)
        #expect(validation.errors.contains { $0.contains("Swift tools 6.3") })
    }

    @Test
    func featureManagementEnablesGeneratedFeatureManifestAndReloads() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-management-\(UUID().uuidString)", isDirectory: true)
        let featureURL = rootURL.appendingPathComponent("generated", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }

        try FileManager.default.createDirectory(
            at: featureURL,
            withIntermediateDirectories: true
        )
        let executableURL = featureURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        if [ "$1" = "--invoke" ]; then
          cat >/dev/null
          printf '{"ok":true,"output":"generated-output"}\\n'
          exit 0
        fi
        printf '{"tools":[{"name":"generated.echo","description":"Generated echo","inputSchema":"{}"}]}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )
        let manifestURL = featureURL.appendingPathComponent(SwiftFeatureRegistry.manifestFilename)
        try """
        {
          "id": "generated-fixture",
          "enabled": false,
          "executable": "feature",
          "tools": [
            {
              "name": "generated.echo",
              "description": "Generated echo",
              "inputSchema": {}
            }
          ]
        }
        """.write(
            to: manifestURL,
            atomically: true,
            encoding: .utf8
        )

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])
        let disabledDescriptors = await runtime.descriptors(
            allowedToolNames: [SwiftFeatureRuntime.generatedFeatureToolsAllowedName]
        )
        #expect(!disabledDescriptors.map(\.name).contains("generated.echo"))

        let listOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-list",
                name: "feature.list",
                argumentsObject: [:],
                argumentsJSON: "{}"
            )
        )
        #expect(listOutput.contains(#""id" : "generated-fixture""#))
        #expect(listOutput.contains(#""enabled" : false"#))

        _ = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-enable",
                name: "feature.enable",
                argumentsObject: ["id": "generated-fixture"],
                argumentsJSON: #"{"id":"generated-fixture"}"#
            )
        )

        let enabledRecords = SwiftFeatureRegistry.discoverFeatureRecords(
            searchRoots: [rootURL]
        )
        #expect(enabledRecords.first?.manifestEnabled == true)

        let enabledDescriptors = await runtime.descriptors(
            allowedToolNames: [SwiftFeatureRuntime.generatedFeatureToolsAllowedName]
        )
        #expect(enabledDescriptors.map(\.name).contains("generated.echo"))

        let output = try await runtime.executeIfAvailable(
            toolCall: DirectAgentToolCall(
                id: "generated-call",
                name: "generated.echo",
                argumentsObject: [:],
                argumentsJSON: "{}"
            ),
            workingDirectory: rootURL
        )
        #expect(output == "generated-output")

        _ = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-disable",
                name: "feature.disable",
                argumentsObject: ["id": "generated-fixture"],
                argumentsJSON: #"{"id":"generated-fixture"}"#
            )
        )
        let disabledRecords = SwiftFeatureRegistry.discoverFeatureRecords(
            searchRoots: [rootURL]
        )
        #expect(disabledRecords.first?.manifestEnabled == false)
    }

    @Test
    func runtimeExecutesFeatureProcess() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-runtime-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let executableURL = rootURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        cat >/dev/null
        printf '{"ok":true,"output":"feature-output"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "fixture",
                    executableURL: executableURL,
                    tools: [
                        ToolDescriptor(
                            name: "feature.fixture.echo",
                            description: "Echo fixture",
                            inputSchema: #"{"type":"object","properties":{}}"#
                        )
                    ]
                )
            ]
        )
        let toolCall = DirectAgentToolCall(
            id: "feature-call-1",
            name: "feature.fixture.echo",
            argumentsObject: [:],
            argumentsJSON: "{}"
        )

        let output = try await runtime.executeIfAvailable(
            toolCall: toolCall,
            workingDirectory: rootURL
        )

        #expect(output == "feature-output")
    }

    @Test
    func runtimeDiscoversDynamicFeatureToolsOnlyWhenRelevant() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-dynamic-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let markerURL = rootURL.appendingPathComponent("list-tools-marker")
        let executableURL = rootURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        if [ "$1" = "--list-tools" ]; then
          printf x >> "\(markerURL.path)"
          printf '{"tools":[{"name":"dynamic.echo","description":"Dynamic echo","inputSchema":"{}"}]}\\n'
          exit 0
        fi
        cat >/dev/null
        printf '{"ok":true,"output":"dynamic-output"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "dynamic-fixture",
                    executableURL: executableURL,
                    tools: [],
                    toolNamePrefixes: ["dynamic."],
                    discoversToolsAtRuntime: true
                )
            ]
        )

        let unrelatedDescriptors = await runtime.descriptors(
            allowedToolNames: ["other."]
        )
        #expect(unrelatedDescriptors.isEmpty)
        #expect(!FileManager.default.fileExists(atPath: markerURL.path))

        let relatedDescriptors = await runtime.descriptors(
            allowedToolNames: ["dynamic."]
        )
        #expect(relatedDescriptors.map(\.name) == ["dynamic.echo"])
        #expect(FileManager.default.fileExists(atPath: markerURL.path))

        let output = try await runtime.executeIfAvailable(
            toolCall: DirectAgentToolCall(
                id: "dynamic-call-1",
                name: "dynamic.echo",
                argumentsObject: [:],
                argumentsJSON: "{}"
            ),
            workingDirectory: rootURL
        )
        #expect(output == "dynamic-output")
    }

    @Test
    func directMCPRuntimeDoesNotAutodiscoverExternalConnectorsByDefault() async {
        let runtime = DirectMCPToolRuntime()

        let descriptors = await runtime.descriptors(
            allowedToolNames: ["xcode.", "figma."]
        )

        #expect(descriptors.isEmpty)
    }

    @Test
    func directToolExecutorRoutesMatchingToolToSwiftFeature() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-routing-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let executableURL = rootURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        cat >/dev/null
        printf '{"ok":true,"output":"feature-dynamic-output"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "dynamic-fixture",
                    executableURL: executableURL,
                    tools: [
                        ToolDescriptor(
                            name: "dynamic.fixture",
                            description: "Runs a dynamic fixture",
                            inputSchema: #"{"type":"object","properties":{}}"#
                        )
                    ]
                )
            ]
        )
        let executor = DirectToolExecutor(
            outputLimit: 24_000,
            swiftFeatureRuntime: runtime,
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )
        let toolCall = DirectAgentToolCall(
            id: "feature-call-1",
            name: "dynamic.fixture",
            argumentsObject: [:],
            argumentsJSON: "{}"
        )

        let result = await executor.execute(
            sessionID: "test-session",
            toolCall: toolCall,
            workingDirectory: rootURL,
            allowedToolNames: ["dynamic.fixture"]
        )

        #expect(result.output == "feature-dynamic-output")
    }

    @Test
    func directToolExecutorAllowsGeneratedFeatureToolsWithFeatureGroupToken() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-generated-token-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let executableURL = rootURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        cat >/dev/null
        printf '{"ok":true,"output":"generated-token-output"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "generated-token-fixture",
                    executableURL: executableURL,
                    tools: [
                        ToolDescriptor(
                            name: "generated.token",
                            description: "Generated token fixture",
                            inputSchema: #"{"type":"object","properties":{}}"#
                        )
                    ],
                    source: .generated
                )
            ]
        )
        let executor = DirectToolExecutor(
            outputLimit: 24_000,
            swiftFeatureRuntime: runtime,
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )

        let descriptors = await executor.descriptors(
            allowedToolNames: [SwiftFeatureRuntime.generatedFeatureToolsAllowedName]
        )
        #expect(descriptors.map(\.name).contains("generated.token"))

        let result = await executor.execute(
            sessionID: "test-session",
            toolCall: DirectAgentToolCall(
                id: "generated-token-call",
                name: "generated.token",
                argumentsObject: [:],
                argumentsJSON: "{}"
            ),
            workingDirectory: rootURL,
            allowedToolNames: [SwiftFeatureRuntime.generatedFeatureToolsAllowedName]
        )

        #expect(result.output == "generated-token-output")
    }

    @Test
    func directToolExecutorDoesNotFallbackToExtractedSearchTools() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-no-fallback-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )

        let executor = DirectToolExecutor(
            outputLimit: 24_000,
            swiftFeatureRuntime: SwiftFeatureRuntime(features: []),
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )
        let toolCall = DirectAgentToolCall(
            id: "no-fallback-call-1",
            name: "search.glob",
            argumentsObject: [
                "pattern": "*.swift"
            ],
            argumentsJSON: #"{"pattern":"*.swift"}"#
        )

        let result = await executor.execute(
            sessionID: "test-session",
            toolCall: toolCall,
            workingDirectory: rootURL,
            allowedToolNames: ["search.glob"]
        )

        #expect(result.output == "Tool error: Unknown tool: search.glob")
    }

    @Test
    func directToolExecutorKeepsFileAndTextToolsInCoreRuntime() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-core-local-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let fileURL = rootURL.appendingPathComponent("sample.txt")
        try "ciao mondo\n".write(to: fileURL, atomically: true, encoding: .utf8)

        let executor = DirectToolExecutor(
            outputLimit: 24_000,
            swiftFeatureRuntime: SwiftFeatureRuntime(features: []),
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )

        let readResult = await executor.execute(
            sessionID: "test-session",
            toolCall: DirectAgentToolCall(
                id: "core-local-call-1",
                name: "local.readFile",
                argumentsObject: ["path": "sample.txt"],
                argumentsJSON: #"{"path":"sample.txt"}"#
            ),
            workingDirectory: rootURL,
            allowedToolNames: ["local.readFile"]
        )
        let wcResult = await executor.execute(
            sessionID: "test-session",
            toolCall: DirectAgentToolCall(
                id: "core-local-call-2",
                name: "text.wc",
                argumentsObject: ["path": "sample.txt"],
                argumentsJSON: #"{"path":"sample.txt"}"#
            ),
            workingDirectory: rootURL,
            allowedToolNames: ["text.wc"]
        )

        #expect(readResult.output.contains("1\tciao mondo"))
        #expect(wcResult.output.contains("words: 2"))
    }

    @Test
    func directToolExecutorKeepsLocalExecInCoreRuntime() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-local-exec-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let executableURL = rootURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        cat >/dev/null
        printf '{"ok":true,"output":"feature-local-exec"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "local-exec-fixture",
                    executableURL: executableURL,
                    tools: [
                        ToolDescriptor(
                            name: "local.exec",
                            description: "Should not replace core local exec",
                            inputSchema: #"{"type":"object","properties":{}}"#
                        )
                    ]
                )
            ]
        )
        let executor = DirectToolExecutor(
            outputLimit: 24_000,
            swiftFeatureRuntime: runtime,
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )
        let toolCall = DirectAgentToolCall(
            id: "local-exec-call-1",
            name: "local.exec",
            argumentsObject: [
                "command": "printf core-local-exec"
            ],
            argumentsJSON: #"{"command":"printf core-local-exec"}"#
        )

        let result = await executor.execute(
            sessionID: "test-session",
            toolCall: toolCall,
            workingDirectory: rootURL,
            allowedToolNames: ["local.exec"]
        )

        #expect(result.output.contains("stdout:\ncore-local-exec"))
        #expect(!result.output.contains("feature-local-exec"))
    }

    @Test
    func directToolExecutorAuthorizesDynamicGitMutationsBeforeFeatureExecution() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-git-auth-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let executableURL = rootURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        cat >/dev/null
        printf '{"ok":true,"output":"feature-git-commit"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "git-fixture",
                    executableURL: executableURL,
                    tools: [
                        ToolDescriptor(
                            name: "git.commit",
                            description: "Should require kernel authorization",
                            inputSchema: #"{"type":"object","properties":{"message":{"type":"string"}},"required":["message"]}"#
                        )
                    ]
                )
            ]
        )
        let executor = DirectToolExecutor(
            outputLimit: 24_000,
            authorizationHandler: { request in
                request.toolName == "git.commit" && request.kind == "git.mutation"
                    ? false
                    : true
            },
            swiftFeatureRuntime: runtime,
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )
        let toolCall = DirectAgentToolCall(
            id: "git-commit-call-1",
            name: "git.commit",
            argumentsObject: [
                "message": "test"
            ],
            argumentsJSON: #"{"message":"test"}"#
        )

        let result = await executor.execute(
            sessionID: "test-session",
            toolCall: toolCall,
            workingDirectory: rootURL,
            allowedToolNames: ["git.commit"]
        )

        #expect(result.output.contains("Git command cancelled."))
        #expect(!result.output.contains("feature-git-commit"))
    }
}

private actor TestAgentRuntimeBackend: AgentRuntimeBackend {
    func createSession(
        id _: String,
        cwd _: String,
        systemPrompt _: String?,
        history _: [AgentRuntimeMessage],
        cacheKey _: String?,
        allowedToolNames _: Set<String>?,
        thinkingSelection _: AgentThinkingSelection?,
        preserveThinking _: Bool
    ) {}

    func createSessionIfNeeded(
        id _: String,
        cwd _: String,
        systemPrompt _: String?,
        history _: [AgentRuntimeMessage],
        cacheKey _: String?,
        allowedToolNames _: Set<String>?,
        thinkingSelection _: AgentThinkingSelection?,
        preserveThinking _: Bool
    ) {}

    func updateSessionOptions(
        id _: String,
        systemPrompt _: String?,
        allowedToolNames _: Set<String>?,
        thinkingSelection _: AgentThinkingSelection?,
        preserveThinking _: Bool
    ) {}

    func closeSession(id _: String) {}

    func shutdown() async {}

    func preloadModel(
        onEvent _: @escaping @Sendable (DirectAgentEvent) async -> Void
    ) async throws -> String {
        "test"
    }

    func activeToolDescriptors() async -> [DirectToolDescriptor] {
        []
    }

    func sendPrompt(
        sessionID _: String,
        prompt _: String,
        attachments _: [AgentRuntimeAttachment],
        onEvent _: @escaping @Sendable (DirectAgentEvent) async -> Void
    ) async throws -> DirectAgentResponse {
        DirectAgentResponse(text: "", stopReason: "end_turn", modelID: "test")
    }
}
