import Foundation
@testable import MLXCoderCore
import Testing

@Suite
struct SwiftFeatureRuntimeTests {
    @Test
    func processRunnerWritesStandardInput() async throws {
        let result = try await AsyncProcessRunner.run(
            executableURL: URL(fileURLWithPath: "/bin/cat"),
            arguments: [],
            stdinData: Data("hello feature\n".utf8),
            timeout: 10
        )

        #expect(result.exitCode == 0)
        #expect(result.stdout == "hello feature\n")
    }

    @Test
    func registryDiscoversExecutableManifest() throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-registry-\(UUID().uuidString)", isDirectory: true)
        let featureURL = rootURL.appendingPathComponent("example", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }

        try FileManager.default.createDirectory(
            at: featureURL,
            withIntermediateDirectories: true
        )
        let executableURL = featureURL.appendingPathComponent("feature")
        try "#!/bin/sh\n".write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )
        try """
        {
          "id": "example",
          "enabled": true,
          "executable": "feature",
          "tools": [
            {
              "name": "feature.example.echo",
              "description": "Echo test",
              "inputSchema": {
                "type": "object",
                "properties": {
                  "text": { "type": "string" }
                },
                "required": ["text"]
              }
            }
          ]
        }
        """.write(
            to: featureURL.appendingPathComponent(SwiftFeatureRegistry.manifestFilename),
            atomically: true,
            encoding: .utf8
        )

        let bundles = SwiftFeatureRegistry.discoverFeatureBundles(
            searchRoots: [rootURL]
        )

        #expect(bundles.count == 1)
        #expect(bundles.first?.id == "example")
        #expect(bundles.first?.tools.first?.name == "feature.example.echo")
        #expect(bundles.first?.tools.first?.requiredInputArgumentNames() == ["text"])
    }

    @Test
    func registrySupportsGeneratedFeaturePackageManifestSchema() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-schema-\(UUID().uuidString)", isDirectory: true)
        let featureURL = rootURL.appendingPathComponent("rich", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }

        try FileManager.default.createDirectory(
            at: featureURL,
            withIntermediateDirectories: true
        )
        let executableURL = featureURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        if [ "$1" = "--list-tools" ]; then
          printf '{"tools":[{"name":"custom.dynamic","description":"Dynamic custom tool","inputSchema":"{}"}]}\\n'
          exit 0
        fi
        cat >/dev/null
        printf '{"ok":true,"output":"custom-output"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )
        try """
        {
          "schemaVersion": 1,
          "id": "custom-feature",
          "displayName": "Custom Feature",
          "description": "Feature generated by an agent.",
          "enabled": true,
          "executable": "feature",
          "discoversToolsAtRuntime": true,
          "toolNamePrefixes": ["custom."],
          "toolNameAliases": ["CustomDynamic"],
          "build": {
            "system": "swiftpm",
            "packagePath": ".",
            "product": "custom-feature",
            "configuration": "release",
            "executablePath": ".build/release/custom-feature"
          },
          "generated": {
            "by": "mlx-coder",
            "prompt": "Need a custom feature",
            "createdAt": "2026-05-30T12:00:00Z"
          },
          "tools": []
        }
        """.write(
            to: featureURL.appendingPathComponent(SwiftFeatureRegistry.manifestFilename),
            atomically: true,
            encoding: .utf8
        )

        let bundles = SwiftFeatureRegistry.discoverFeatureBundles(
            searchRoots: [rootURL]
        )
        #expect(bundles.first?.id == "custom-feature")
        #expect(bundles.first?.toolNamePrefixes == ["custom."])
        #expect(bundles.first?.toolNameAliases == ["CustomDynamic"])
        #expect(bundles.first?.discoversToolsAtRuntime == true)

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])
        let statuses = await runtime.featureStatuses()
        #expect(statuses.first?.displayName == "Custom Feature")
        #expect(statuses.first?.description == "Feature generated by an agent.")
        #expect(statuses.first?.build?.product == "custom-feature")
        #expect(statuses.first?.generated?.by == "mlx-coder")

        let descriptors = await runtime.descriptors(
            allowedToolNames: ["custom."]
        )
        #expect(descriptors.map(\.name) == ["custom.dynamic"])
    }

    @Test
    func featureScaffoldCreatesSwift63PackageBuildsAndEnables() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-scaffold-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])
        let scaffoldOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-scaffold",
                name: "feature.scaffold",
                argumentsObject: [
                    "id": "example-feature",
                    "toolName": "example.echo"
                ],
                argumentsJSON: #"{"id":"example-feature","toolName":"example.echo"}"#
            )
        )
        let scaffold = try JSONDecoder().decode(
            SwiftFeatureScaffoldReport.self,
            from: Data(scaffoldOutput.utf8)
        )

        let packageFirstLine = try String(
            contentsOf: URL(fileURLWithPath: scaffold.packagePath),
            encoding: .utf8
        ).components(separatedBy: .newlines).first
        #expect(packageFirstLine == "// swift-tools-version: 6.3")

        let validateOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-validate",
                name: "feature.validate",
                argumentsObject: ["id": "example-feature"],
                argumentsJSON: #"{"id":"example-feature"}"#
            )
        )
        let validation = try JSONDecoder().decode(
            SwiftFeatureValidationReport.self,
            from: Data(validateOutput.utf8)
        )
        #expect(validation.ok)

        let buildOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-build",
                name: "feature.build",
                argumentsObject: ["id": "example-feature"],
                argumentsJSON: #"{"id":"example-feature"}"#
            )
        )
        let build = try JSONDecoder().decode(
            SwiftFeatureBuildReport.self,
            from: Data(buildOutput.utf8)
        )
        #expect(build.ok)
        #expect(FileManager.default.isExecutableFile(atPath: build.executablePath))

        _ = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-enable",
                name: "feature.enable",
                argumentsObject: ["id": "example-feature"],
                argumentsJSON: #"{"id":"example-feature"}"#
            )
        )

        let descriptors = await runtime.descriptors(
            allowedToolNames: [SwiftFeatureRuntime.featurePackageToolsAllowedName]
        )
        #expect(descriptors.map(\.name).contains("example.echo"))

        let output = try await runtime.executeIfAvailable(
            toolCall: DirectAgentToolCall(
                id: "example-echo",
                name: "example.echo",
                argumentsObject: ["text": "ciao"],
                argumentsJSON: #"{"text":"ciao"}"#
            ),
            workingDirectory: rootURL
        )
        #expect(output == "ciao")
    }

    @Test
    func featureDeleteRemovesGeneratedPackageButRejectsBundledFeatures() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-delete-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])
        _ = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-scaffold-delete",
                name: "feature.scaffold",
                argumentsObject: [
                    "id": "throwaway-feature",
                    "toolName": "throwaway.run"
                ],
                argumentsJSON: #"{"id":"throwaway-feature","toolName":"throwaway.run"}"#
            )
        )
        let featureURL = rootURL.appendingPathComponent("throwaway-feature", isDirectory: true)
        #expect(FileManager.default.fileExists(atPath: featureURL.path))

        let deleteOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-delete",
                name: "feature.delete",
                argumentsObject: ["id": "throwaway-feature"],
                argumentsJSON: #"{"id":"throwaway-feature"}"#
            )
        )
        let deleteReport = try JSONDecoder().decode(
            SwiftFeatureDeleteReport.self,
            from: Data(deleteOutput.utf8)
        )
        #expect(deleteReport.ok)
        #expect(deleteReport.removed)
        #expect(deleteReport.directoryPath == featureURL.path)
        #expect(!FileManager.default.fileExists(atPath: featureURL.path))

        let listOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-list-after-delete",
                name: "feature.list",
                argumentsObject: [:],
                argumentsJSON: "{}"
            )
        )
        #expect(!listOutput.contains("throwaway-feature"))

        do {
            _ = try await runtime.executeManagementTool(
                toolCall: DirectAgentToolCall(
                    id: "feature-delete-bundled",
                    name: "feature.delete",
                    argumentsObject: ["id": "mlx-git-tools"],
                    argumentsJSON: #"{"id":"mlx-git-tools"}"#
                )
            )
            Issue.record("feature.delete unexpectedly removed a bundled feature.")
        } catch {
            #expect(error.localizedDescription.contains("cannot be deleted"))
        }
    }

    @Test
    func featureScaffoldCreatesMCPBridgePackage() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-mcp-bridge-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])
        let scaffoldOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-scaffold-mcp",
                name: "feature.scaffold",
                argumentsObject: [
                    "id": "linear-mcp",
                    "template": "mcp-bridge",
                    "displayName": "Linear MCP",
                    "serviceName": "Linear",
                    "toolPrefix": "linear.",
                    "endpointURL": "http://127.0.0.1:65535/mcp"
                ],
                argumentsJSON: "{}"
            )
        )
        let scaffold = try JSONDecoder().decode(
            SwiftFeatureScaffoldReport.self,
            from: Data(scaffoldOutput.utf8)
        )

        let packageContents = try String(
            contentsOf: URL(fileURLWithPath: scaffold.packagePath),
            encoding: .utf8
        )
        let sourceContents = try String(
            contentsOf: URL(fileURLWithPath: scaffold.sourcePath),
            encoding: .utf8
        )
        let manifest = try JSONDecoder().decode(
            SwiftFeatureManifest.self,
            from: Data(
                contentsOf: URL(fileURLWithPath: scaffold.manifestPath)
            )
        )

        #expect(packageContents.components(separatedBy: .newlines).first == "// swift-tools-version: 6.3")
        #expect(packageContents.contains(#".product(name: "MLXCoderCore", package: "mlx-server")"#))
        #expect(sourceContents.contains("RemoteMCPToolExecutor"))
        #expect(sourceContents.contains("http://127.0.0.1:65535/mcp"))
        #expect(manifest.discoversToolsAtRuntime)
        #expect(manifest.toolNamePrefixes == ["linear."])
        #expect(manifest.tools.isEmpty)

        let validateOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-validate-mcp",
                name: "feature.validate",
                argumentsObject: ["id": "linear-mcp"],
                argumentsJSON: #"{"id":"linear-mcp"}"#
            )
        )
        let validation = try JSONDecoder().decode(
            SwiftFeatureValidationReport.self,
            from: Data(validateOutput.utf8)
        )
        #expect(validation.ok)

        let buildOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-build-mcp",
                name: "feature.build",
                argumentsObject: [
                    "id": "linear-mcp",
                    "timeoutSeconds": 120
                ],
                argumentsJSON: "{}"
            )
        )
        let build = try JSONDecoder().decode(
            SwiftFeatureBuildReport.self,
            from: Data(buildOutput.utf8)
        )
        #expect(build.ok)
        #expect(FileManager.default.isExecutableFile(atPath: build.executablePath))
    }

    @Test
    func featureScaffoldRejectsPathsOutsideGeneratedFeatureRoot() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-scaffold-root-\(UUID().uuidString)", isDirectory: true)
        let outsideURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-scaffold-outside-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
            try? FileManager.default.removeItem(at: outsideURL)
        }

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])

        do {
            _ = try await runtime.executeManagementTool(
                toolCall: DirectAgentToolCall(
                    id: "feature-scaffold-outside",
                    name: "feature.scaffold",
                    argumentsObject: [
                        "id": "outside-feature",
                        "toolName": "outside.echo",
                        "path": outsideURL.path
                    ],
                    argumentsJSON: "{}"
                )
            )
            Issue.record("feature.scaffold unexpectedly allowed a path outside the generated feature root.")
        } catch {
            #expect(error.localizedDescription.contains("feature.scaffold can only create packages"))
            #expect(!FileManager.default.fileExists(atPath: outsideURL.path))
        }
    }

    @Test
    func featureInstallCopiesBuildsAndEnablesExternalFeature() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-install-root-\(UUID().uuidString)", isDirectory: true)
        let sourceURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-install-source-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
            try? FileManager.default.removeItem(at: sourceURL)
        }

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])
        let sourceRuntime = SwiftFeatureRuntime(featureSearchRoots: [sourceURL])
        _ = try await sourceRuntime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-install-scaffold",
                name: "feature.scaffold",
                argumentsObject: [
                    "id": "install-feature",
                    "toolName": "installed.echo"
                ],
                argumentsJSON: "{}"
            )
        )
        let sourceFeatureURL = sourceURL.appendingPathComponent("install-feature", isDirectory: true)

        let installOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-install",
                name: "feature.install",
                argumentsObject: [
                    "path": sourceFeatureURL.path
                ],
                argumentsJSON: "{}"
            )
        )
        let install = try JSONDecoder().decode(
            SwiftFeatureInstallReport.self,
            from: Data(installOutput.utf8)
        )

        #expect(install.ok)
        #expect(install.copied)
        #expect(install.built)
        #expect(install.enabled)
        #expect(install.destinationPath == rootURL.appendingPathComponent("install-feature").path)
        #expect(FileManager.default.fileExists(atPath: install.manifestPath))

        let descriptors = await runtime.descriptors(
            allowedToolNames: [SwiftFeatureRuntime.featurePackageToolsAllowedName]
        )
        #expect(descriptors.contains { $0.name == "installed.echo" })

        let output = try await runtime.executeIfAvailable(
            toolCall: DirectAgentToolCall(
                id: "feature-install-invoke",
                name: "installed.echo",
                argumentsObject: ["text": "installato"],
                argumentsJSON: #"{"text":"installato"}"#
            ),
            workingDirectory: rootURL
        )
        #expect(output == "installato")
    }

    @Test
    func featureValidateRejectsNonSwift63Package() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-swift-version-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])
        let scaffoldOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-scaffold",
                name: "feature.scaffold",
                argumentsObject: [
                    "id": "wrong-version-feature",
                    "toolName": "wrongversion.echo"
                ],
                argumentsJSON: #"{"id":"wrong-version-feature","toolName":"wrongversion.echo"}"#
            )
        )
        let scaffold = try JSONDecoder().decode(
            SwiftFeatureScaffoldReport.self,
            from: Data(scaffoldOutput.utf8)
        )
        var packageContents = try String(
            contentsOf: URL(fileURLWithPath: scaffold.packagePath),
            encoding: .utf8
        )
        packageContents = packageContents.replacingOccurrences(
            of: "// swift-tools-version: 6.3",
            with: "// swift-tools-version: 6.2"
        )
        try packageContents.write(
            to: URL(fileURLWithPath: scaffold.packagePath),
            atomically: true,
            encoding: .utf8
        )

        let validateOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-validate",
                name: "feature.validate",
                argumentsObject: ["id": "wrong-version-feature"],
                argumentsJSON: #"{"id":"wrong-version-feature"}"#
            )
        )
        let validation = try JSONDecoder().decode(
            SwiftFeatureValidationReport.self,
            from: Data(validateOutput.utf8)
        )

        #expect(!validation.ok)
        #expect(validation.errors.contains { $0.contains("Swift tools 6.3") })
    }

    @Test
    func featureManagementEnablesGeneratedFeatureManifestAndReloads() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-management-\(UUID().uuidString)", isDirectory: true)
        let featureURL = rootURL.appendingPathComponent("generated", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }

        try FileManager.default.createDirectory(
            at: featureURL,
            withIntermediateDirectories: true
        )
        let executableURL = featureURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        if [ "$1" = "--invoke" ]; then
          cat >/dev/null
          printf '{"ok":true,"output":"generated-output"}\\n'
          exit 0
        fi
        printf '{"tools":[{"name":"generated.echo","description":"Generated echo","inputSchema":"{}"}]}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )
        let manifestURL = featureURL.appendingPathComponent(SwiftFeatureRegistry.manifestFilename)
        try """
        {
          "id": "generated-fixture",
          "enabled": false,
          "executable": "feature",
          "tools": [
            {
              "name": "generated.echo",
              "description": "Generated echo",
              "inputSchema": {}
            }
          ]
        }
        """.write(
            to: manifestURL,
            atomically: true,
            encoding: .utf8
        )

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [rootURL])
        let disabledDescriptors = await runtime.descriptors(
            allowedToolNames: [SwiftFeatureRuntime.featurePackageToolsAllowedName]
        )
        #expect(!disabledDescriptors.map(\.name).contains("generated.echo"))

        let listOutput = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-list",
                name: "feature.list",
                argumentsObject: [:],
                argumentsJSON: "{}"
            )
        )
        #expect(listOutput.contains(#""id" : "generated-fixture""#))
        #expect(listOutput.contains(#""enabled" : false"#))

        _ = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-enable",
                name: "feature.enable",
                argumentsObject: ["id": "generated-fixture"],
                argumentsJSON: #"{"id":"generated-fixture"}"#
            )
        )

        let enabledRecords = SwiftFeatureRegistry.discoverFeatureRecords(
            searchRoots: [rootURL]
        )
        #expect(enabledRecords.first?.manifestEnabled == true)

        let enabledDescriptors = await runtime.descriptors(
            allowedToolNames: [SwiftFeatureRuntime.featurePackageToolsAllowedName]
        )
        #expect(enabledDescriptors.map(\.name).contains("generated.echo"))

        let output = try await runtime.executeIfAvailable(
            toolCall: DirectAgentToolCall(
                id: "generated-call",
                name: "generated.echo",
                argumentsObject: [:],
                argumentsJSON: "{}"
            ),
            workingDirectory: rootURL
        )
        #expect(output == "generated-output")

        _ = try await runtime.executeManagementTool(
            toolCall: DirectAgentToolCall(
                id: "feature-disable",
                name: "feature.disable",
                argumentsObject: ["id": "generated-fixture"],
                argumentsJSON: #"{"id":"generated-fixture"}"#
            )
        )
        let disabledRecords = SwiftFeatureRegistry.discoverFeatureRecords(
            searchRoots: [rootURL]
        )
        #expect(disabledRecords.first?.manifestEnabled == false)
    }

    @Test
    func runtimeExecutesFeatureProcess() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-runtime-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let executableURL = rootURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        cat >/dev/null
        printf '{"ok":true,"output":"feature-output"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "fixture",
                    executableURL: executableURL,
                    tools: [
                        ToolDescriptor(
                            name: "feature.fixture.echo",
                            description: "Echo fixture",
                            inputSchema: #"{"type":"object","properties":{}}"#
                        )
                    ]
                )
            ]
        )
        let toolCall = DirectAgentToolCall(
            id: "feature-call-1",
            name: "feature.fixture.echo",
            argumentsObject: [:],
            argumentsJSON: "{}"
        )

        let output = try await runtime.executeIfAvailable(
            toolCall: toolCall,
            workingDirectory: rootURL
        )

        #expect(output == "feature-output")
    }

    @Test
    func runtimeDiscoversDynamicFeatureToolsOnlyWhenRelevant() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-dynamic-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let markerURL = rootURL.appendingPathComponent("list-tools-marker")
        let executableURL = rootURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        if [ "$1" = "--list-tools" ]; then
          printf x >> "\(markerURL.path)"
          printf '{"tools":[{"name":"dynamic.echo","description":"Dynamic echo","inputSchema":"{}"}]}\\n'
          exit 0
        fi
        cat >/dev/null
        printf '{"ok":true,"output":"dynamic-output"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "dynamic-fixture",
                    executableURL: executableURL,
                    tools: [],
                    toolNamePrefixes: ["dynamic."],
                    discoversToolsAtRuntime: true
                )
            ]
        )

        let allDescriptors = await runtime.descriptors()
        #expect(allDescriptors.isEmpty)
        #expect(!FileManager.default.fileExists(atPath: markerURL.path))

        let unrelatedDescriptors = await runtime.descriptors(
            allowedToolNames: ["other."]
        )
        #expect(unrelatedDescriptors.isEmpty)
        #expect(!FileManager.default.fileExists(atPath: markerURL.path))

        let relatedDescriptors = await runtime.descriptors(
            allowedToolNames: ["dynamic."]
        )
        #expect(relatedDescriptors.map(\.name) == ["dynamic.echo"])
        #expect(FileManager.default.fileExists(atPath: markerURL.path))

        let output = try await runtime.executeIfAvailable(
            toolCall: DirectAgentToolCall(
                id: "dynamic-call-1",
                name: "dynamic.echo",
                argumentsObject: [:],
                argumentsJSON: "{}"
            ),
            workingDirectory: rootURL
        )
        #expect(output == "dynamic-output")
    }

    @Test
    func featureStatusesDoNotDiscoverRuntimeToolsByDefault() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-status-no-discovery-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let markerURL = rootURL.appendingPathComponent("list-tools-marker")
        let executableURL = rootURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        if [ "$1" = "--list-tools" ]; then
          printf x >> "\(markerURL.path)"
          printf '{"tools":[{"name":"dynamic.status","description":"Dynamic status","inputSchema":"{}"}]}\\n'
          exit 0
        fi
        cat >/dev/null
        printf '{"ok":true,"output":"status-output"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "status-fixture",
                    executableURL: executableURL,
                    tools: [],
                    toolNamePrefixes: ["dynamic."],
                    discoversToolsAtRuntime: true
                )
            ]
        )

        let statuses = await runtime.featureStatuses(includeTools: true)

        #expect(statuses.first?.id == "status-fixture")
        #expect(statuses.first?.tools == [])
        #expect(!FileManager.default.fileExists(atPath: markerURL.path))
    }

    @Test
    func directMCPRuntimeDoesNotAutodiscoverExternalConnectorsByDefault() async {
        let runtime = DirectMCPToolRuntime()

        let descriptors = await runtime.descriptors(
            allowedToolNames: ["xcode.", "figma."]
        )

        #expect(descriptors.isEmpty)
    }

    @Test
    func directToolExecutorDoesNotDiscoverXcodeThroughSwiftFeatureRuntime() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-xcode-feature-discovery-skip-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let markerURL = rootURL.appendingPathComponent("xcode-feature-discovered")
        let executableURL = rootURL.appendingPathComponent("xcode-feature")
        try """
        #!/bin/sh
        if [ "$1" = "--list-tools" ]; then
          printf x >> "\(markerURL.path)"
          printf '{"tools":[{"name":"xcode.BuildProject","description":"Dynamic Xcode build","inputSchema":"{}"}]}\\n'
          exit 0
        fi
        cat >/dev/null
        printf '{"ok":true,"output":"feature-xcode-output"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "mlx-xcode-tools",
                    executableURL: executableURL,
                    tools: [],
                    toolNamePrefixes: ["xcode."],
                    toolNameAliases: ["BuildProject"],
                    discoversToolsAtRuntime: true,
                    source: .bundled
                )
            ]
        )
        let executor = DirectToolExecutor(
            outputLimit: 24_000,
            swiftFeatureRuntime: runtime,
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )

        let descriptors = await executor.descriptors(
            allowedToolNames: ["xcode."]
        )

        #expect(descriptors.isEmpty)
        #expect(!FileManager.default.fileExists(atPath: markerURL.path))
    }

    @Test
    func directToolExecutorUsesExistingMCPXcodeDescriptorsWithoutFeatureDiscovery() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-xcode-mcp-descriptor-reuse-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let markerURL = rootURL.appendingPathComponent("xcode-feature-discovered")
        let executableURL = rootURL.appendingPathComponent("xcode-feature")
        try """
        #!/bin/sh
        if [ "$1" = "--list-tools" ]; then
          printf x >> "\(markerURL.path)"
          printf '{"tools":[{"name":"xcode.BuildProject","description":"Dynamic Xcode build","inputSchema":"{}"}]}\\n'
          exit 0
        fi
        cat >/dev/null
        printf '{"ok":true,"output":"feature-xcode-output"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "mlx-xcode-tools",
                    executableURL: executableURL,
                    tools: [],
                    toolNamePrefixes: ["xcode."],
                    toolNameAliases: ["BuildProject"],
                    discoversToolsAtRuntime: true,
                    source: .bundled
                )
            ]
        )
        let mcpRuntime = DirectMCPToolRuntime()
        let xcodeExecutor = XcodeToolExecutor(
            configuration: MCPServerConfiguration(
                executablePath: "/usr/bin/false",
                arguments: [],
                environment: [:]
            )
        )
        await mcpRuntime.installBorrowedXcodeExecutor(
            xcodeExecutor,
            tools: [
                ToolDescriptor(
                    name: "BuildProject",
                    description: "Builds an Xcode project",
                    inputSchema: "{}"
                )
            ]
        )
        let executor = DirectToolExecutor(
            outputLimit: 24_000,
            mcpRuntime: mcpRuntime,
            swiftFeatureRuntime: runtime,
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )

        let descriptors = await executor.descriptors(
            allowedToolNames: ["xcode."]
        )

        #expect(descriptors.map(\.name) == ["xcode.BuildProject"])
        #expect(!FileManager.default.fileExists(atPath: markerURL.path))
    }

    @Test
    func defaultFeatureStatusesIncludeBundledPackagesEvenWhenManaged() {
        let ids = Set(
            SwiftFeatureRuntime.defaultFeatureStatuses(
                includeTools: false,
                includeDisabled: true
            ).map(\.id)
        )

        #expect(ids.contains("mlx-search-tools"))
        #expect(ids.contains("mlx-web-tools"))
        #expect(ids.contains("mlx-git-tools"))
        #expect(ids.contains("mlx-xcode-tools"))
        #expect(ids.contains("mlx-figma-tools"))
    }

    @Test
    func defaultGitFeatureStatusIncludesPushTool() {
        let gitStatus = SwiftFeatureRuntime.defaultFeatureStatuses(
            includeTools: true,
            includeDisabled: true
        ).first { $0.id == "mlx-git-tools" }

        #expect(gitStatus?.tools.contains("git.commit") == true)
        #expect(gitStatus?.tools.contains("git.push") == true)
    }

    @Test
    func bundledExecutableCandidatesIncludeSourcePackageBuildProductsFromOtherWorkingDirectory() throws {
        let outsideWorkingDirectory = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-feature-cwd-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: outsideWorkingDirectory)
        }
        try FileManager.default.createDirectory(
            at: outsideWorkingDirectory,
            withIntermediateDirectories: true
        )
        let packageRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .standardizedFileURL
        let packageBuildPrefix = packageRoot
            .appendingPathComponent(".build", isDirectory: true)
            .path + "/"

        let candidates = SwiftFeatureRuntime.bundledExecutableCandidateURLs(
            named: "mlx-git-tools-feature",
            fileManager: .default,
            workingDirectoryURL: outsideWorkingDirectory
        )

        #expect(
            candidates.contains {
                $0.path.hasPrefix(packageBuildPrefix)
                    && $0.lastPathComponent == "mlx-git-tools-feature"
            }
        )
    }

    @Test
    func bundledExecutableCandidatesIncludeReleaseFeaturesDirectoryNextToBinary() throws {
        let binaryDirectoryURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-feature-release-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: binaryDirectoryURL)
        }
        try FileManager.default.createDirectory(
            at: binaryDirectoryURL,
            withIntermediateDirectories: true
        )

        let candidates = SwiftFeatureRuntime.bundledExecutableCandidateURLs(
            named: "mlx-web-tools-feature",
            fileManager: .default,
            pathEnvironment: nil,
            commandLineArgument: nil,
            executableDirectoryURLs: [binaryDirectoryURL]
        )
        let expectedURL = binaryDirectoryURL
            .appendingPathComponent("features", isDirectory: true)
            .appendingPathComponent("mlx-web-tools-feature")
            .standardizedFileURL

        #expect(candidates.contains { $0.path == expectedURL.path })
    }

    @Test
    func bundledExecutableCandidatesIncludeInstallerFeatureDirectoryNextToBinary() throws {
        let binaryDirectoryURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-feature-install-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: binaryDirectoryURL)
        }
        try FileManager.default.createDirectory(
            at: binaryDirectoryURL,
            withIntermediateDirectories: true
        )

        let candidates = SwiftFeatureRuntime.bundledExecutableCandidateURLs(
            named: "mlx-git-tools-feature",
            fileManager: .default,
            pathEnvironment: nil,
            commandLineArgument: nil,
            executableDirectoryURLs: [binaryDirectoryURL]
        )
        let expectedURL = binaryDirectoryURL
            .appendingPathComponent("mlx-server-features", isDirectory: true)
            .appendingPathComponent("mlx-git-tools-feature")
            .standardizedFileURL

        #expect(candidates.contains { $0.path == expectedURL.path })
    }

    @Test
    func bundledExecutableCandidatesIncludeHomebrewLibexecFeatures() throws {
        let formulaRootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-feature-homebrew-\(UUID().uuidString)", isDirectory: true)
        let binaryDirectoryURL = formulaRootURL
            .appendingPathComponent("bin", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: formulaRootURL)
        }
        try FileManager.default.createDirectory(
            at: binaryDirectoryURL,
            withIntermediateDirectories: true
        )

        let candidates = SwiftFeatureRuntime.bundledExecutableCandidateURLs(
            named: "mlx-xcode-tools-feature",
            fileManager: .default,
            pathEnvironment: nil,
            commandLineArgument: nil,
            executableDirectoryURLs: [binaryDirectoryURL]
        )
        let expectedURL = formulaRootURL
            .appendingPathComponent("libexec", isDirectory: true)
            .appendingPathComponent("features", isDirectory: true)
            .appendingPathComponent("mlx-xcode-tools-feature")
            .standardizedFileURL

        #expect(candidates.contains { $0.path == expectedURL.path })
    }

    @Test
    func bundledExecutableCandidatesResolveInvocationThroughPath() throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-feature-path-\(UUID().uuidString)", isDirectory: true)
        let binaryDirectoryURL = rootURL.appendingPathComponent("bin", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: binaryDirectoryURL,
            withIntermediateDirectories: true
        )
        let coderURL = binaryDirectoryURL.appendingPathComponent("mlx-coder")
        try "#!/bin/sh\n".write(to: coderURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: coderURL.path
        )

        let candidates = SwiftFeatureRuntime.bundledExecutableCandidateURLs(
            named: "mlx-figma-tools-feature",
            fileManager: .default,
            pathEnvironment: binaryDirectoryURL.path,
            commandLineArgument: "mlx-coder"
        )
        let expectedURL = binaryDirectoryURL
            .appendingPathComponent("mlx-figma-tools-feature")
            .standardizedFileURL

        #expect(candidates.contains { $0.path == expectedURL.path })
    }

    @Test
    func directToolExecutorRoutesMatchingToolToSwiftFeature() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-routing-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let executableURL = rootURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        cat >/dev/null
        printf '{"ok":true,"output":"feature-dynamic-output"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "dynamic-fixture",
                    executableURL: executableURL,
                    tools: [
                        ToolDescriptor(
                            name: "dynamic.fixture",
                            description: "Runs a dynamic fixture",
                            inputSchema: #"{"type":"object","properties":{}}"#
                        )
                    ]
                )
            ]
        )
        let executor = DirectToolExecutor(
            outputLimit: 24_000,
            swiftFeatureRuntime: runtime,
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )
        let toolCall = DirectAgentToolCall(
            id: "feature-call-1",
            name: "dynamic.fixture",
            argumentsObject: [:],
            argumentsJSON: "{}"
        )

        let result = await executor.execute(
            sessionID: "test-session",
            toolCall: toolCall,
            workingDirectory: rootURL,
            allowedToolNames: ["dynamic.fixture"]
        )

        #expect(result.output == "feature-dynamic-output")
    }

    @Test
    func directToolExecutorAllowsFeaturePackageToolsWithFeatureGroupToken() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-generated-token-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let executableURL = rootURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        cat >/dev/null
        printf '{"ok":true,"output":"generated-token-output"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "generated-token-fixture",
                    executableURL: executableURL,
                    tools: [
                        ToolDescriptor(
                            name: "generated.token",
                            description: "Generated token fixture",
                            inputSchema: #"{"type":"object","properties":{}}"#
                        )
                    ],
                    source: .generated
                ),
                SwiftFeatureBundle(
                    id: "bundled-token-fixture",
                    executableURL: executableURL,
                    tools: [
                        ToolDescriptor(
                            name: "bundled.token",
                            description: "Bundled token fixture",
                            inputSchema: #"{"type":"object","properties":{}}"#
                        )
                    ],
                    source: .bundled
                )
            ]
        )
        let executor = DirectToolExecutor(
            outputLimit: 24_000,
            swiftFeatureRuntime: runtime,
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )

        let descriptors = await executor.descriptors(
            allowedToolNames: [SwiftFeatureRuntime.featurePackageToolsAllowedName]
        )
        #expect(descriptors.map(\.name).contains("generated.token"))
        #expect(descriptors.map(\.name).contains("bundled.token"))

        let generatedResult = await executor.execute(
            sessionID: "test-session",
            toolCall: DirectAgentToolCall(
                id: "generated-token-call",
                name: "generated.token",
                argumentsObject: [:],
                argumentsJSON: "{}"
            ),
            workingDirectory: rootURL,
            allowedToolNames: [SwiftFeatureRuntime.featurePackageToolsAllowedName]
        )
        let bundledResult = await executor.execute(
            sessionID: "test-session",
            toolCall: DirectAgentToolCall(
                id: "bundled-token-call",
                name: "bundled.token",
                argumentsObject: [:],
                argumentsJSON: "{}"
            ),
            workingDirectory: rootURL,
            allowedToolNames: [SwiftFeatureRuntime.featurePackageToolsAllowedName]
        )

        #expect(generatedResult.output == "generated-token-output")
        #expect(bundledResult.output == "generated-token-output")
    }

    @Test
    func directToolExecutorDoesNotFallbackToExtractedSearchTools() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-no-fallback-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )

        let executor = DirectToolExecutor(
            outputLimit: 24_000,
            swiftFeatureRuntime: SwiftFeatureRuntime(features: []),
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )
        let toolCall = DirectAgentToolCall(
            id: "no-fallback-call-1",
            name: "search.glob",
            argumentsObject: [
                "pattern": "*.swift"
            ],
            argumentsJSON: #"{"pattern":"*.swift"}"#
        )

        let result = await executor.execute(
            sessionID: "test-session",
            toolCall: toolCall,
            workingDirectory: rootURL,
            allowedToolNames: ["search.glob"]
        )

        #expect(result.output == "Tool error: Unknown tool: search.glob")
    }

    @Test
    func directToolExecutorKeepsFileAndTextToolsInCoreRuntime() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-core-local-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let fileURL = rootURL.appendingPathComponent("sample.txt")
        try "ciao mondo\n".write(to: fileURL, atomically: true, encoding: .utf8)

        let executor = DirectToolExecutor(
            outputLimit: 24_000,
            swiftFeatureRuntime: SwiftFeatureRuntime(features: []),
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )

        let readResult = await executor.execute(
            sessionID: "test-session",
            toolCall: DirectAgentToolCall(
                id: "core-local-call-1",
                name: "local.readFile",
                argumentsObject: ["path": "sample.txt"],
                argumentsJSON: #"{"path":"sample.txt"}"#
            ),
            workingDirectory: rootURL,
            allowedToolNames: ["local.readFile"]
        )
        let wcResult = await executor.execute(
            sessionID: "test-session",
            toolCall: DirectAgentToolCall(
                id: "core-local-call-2",
                name: "text.wc",
                argumentsObject: ["path": "sample.txt"],
                argumentsJSON: #"{"path":"sample.txt"}"#
            ),
            workingDirectory: rootURL,
            allowedToolNames: ["text.wc"]
        )

        #expect(readResult.output.contains("1\tciao mondo"))
        #expect(wcResult.output.contains("words: 2"))
    }

    @Test
    func directToolExecutorKeepsLocalExecInCoreRuntime() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-local-exec-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let executableURL = rootURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        cat >/dev/null
        printf '{"ok":true,"output":"feature-local-exec"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "local-exec-fixture",
                    executableURL: executableURL,
                    tools: [
                        ToolDescriptor(
                            name: "local.exec",
                            description: "Should not replace core local exec",
                            inputSchema: #"{"type":"object","properties":{}}"#
                        )
                    ]
                )
            ]
        )
        let executor = DirectToolExecutor(
            outputLimit: 24_000,
            swiftFeatureRuntime: runtime,
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )
        let toolCall = DirectAgentToolCall(
            id: "local-exec-call-1",
            name: "local.exec",
            argumentsObject: [
                "command": "printf core-local-exec"
            ],
            argumentsJSON: #"{"command":"printf core-local-exec"}"#
        )

        let result = await executor.execute(
            sessionID: "test-session",
            toolCall: toolCall,
            workingDirectory: rootURL,
            allowedToolNames: ["local.exec"]
        )

        #expect(result.output.contains("stdout:\ncore-local-exec"))
        #expect(!result.output.contains("feature-local-exec"))
    }

    @Test
    func directToolExecutorDoesNotAuthorizeDynamicGitToolsBeforeFeatureExecution() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-git-auth-\(UUID().uuidString)", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: rootURL,
            withIntermediateDirectories: true
        )
        let executableURL = rootURL.appendingPathComponent("feature")
        try """
        #!/bin/sh
        cat >/dev/null
        printf '{"ok":true,"output":"feature-git-commit"}\\n'
        """.write(to: executableURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: executableURL.path
        )

        let runtime = SwiftFeatureRuntime(
            features: [
                SwiftFeatureBundle(
                    id: "git-fixture",
                    executableURL: executableURL,
                    tools: [
                        ToolDescriptor(
                            name: "git.commit",
                            description: "Should execute through the feature runtime",
                            inputSchema: #"{"type":"object","properties":{"message":{"type":"string"}},"required":["message"]}"#
                        )
                    ]
                )
            ]
        )
        let executor = DirectToolExecutor(
            outputLimit: 24_000,
            authorizationHandler: { request in
                Issue.record("Unexpected authorization request: \(request.toolName) / \(request.kind)")
                return false
            },
            swiftFeatureRuntime: runtime,
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )
        let toolCall = DirectAgentToolCall(
            id: "git-commit-call-1",
            name: "git.commit",
            argumentsObject: [
                "message": "test"
            ],
            argumentsJSON: #"{"message":"test"}"#
        )

        let result = await executor.execute(
            sessionID: "test-session",
            toolCall: toolCall,
            workingDirectory: rootURL,
            allowedToolNames: ["git.commit"]
        )

        #expect(result.output.contains("feature-git-commit"))
        #expect(!result.output.contains("Git command cancelled."))
    }

    @Test
    func scriptedModelGeneratesBuildsEnablesAndUsesFeature() async throws {
        let rootURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("mlx-swift-feature-scripted-model-\(UUID().uuidString)", isDirectory: true)
        let workspaceURL = rootURL.appendingPathComponent("workspace", isDirectory: true)
        let featureRootURL = rootURL.appendingPathComponent("features", isDirectory: true)
        defer {
            try? FileManager.default.removeItem(at: rootURL)
        }
        try FileManager.default.createDirectory(
            at: workspaceURL,
            withIntermediateDirectories: true
        )

        let runtime = SwiftFeatureRuntime(featureSearchRoots: [featureRootURL])
        let executor = DirectToolExecutor(
            outputLimit: 200_000,
            swiftFeatureRuntime: runtime,
            subAgentBackendFactory: { TestAgentRuntimeBackend() }
        )
        let scriptedModel = ScriptedFeatureAuthoringModelBackend(
            toolExecutor: executor
        )
        let runner = AgentCoreSessionRunner(
            backendFactory: { _, _ in scriptedModel }
        )
        let recorder = DirectAgentEventRecorder()
        let configuration = AgentCoreSessionConfiguration(
            sessionID: "scripted-model-feature-test",
            modelID: "scripted-model",
            workingDirectory: workspaceURL,
            systemPrompt: MLXSystemPromptBuilder.defaultAgentInstructions(),
            cacheKey: nil,
            history: [],
            allowedToolNames: [
                "feature.scaffold",
                "feature.validate",
                "feature.build",
                "feature.enable",
                "local.replace",
                SwiftFeatureRuntime.featurePackageToolsAllowedName
            ],
            maxToolRounds: 20
        )

        let response = try await runner.sendPrompt(
            configuration: configuration,
            prompt: "Genera una feature Swift riusabile che inverta il testo e usala con la parola desserts.",
            attachments: [],
            onEvent: { event in
                await recorder.record(event)
            }
        )

        let toolNames = await recorder.startedToolNames()
        let reverseOutput = await recorder.completedOutput(for: "scripted.reverse")
        let packageURL = featureRootURL
            .appendingPathComponent("scripted-reverse", isDirectory: true)
            .appendingPathComponent("Package.swift")
        let packageFirstLine = try String(
            contentsOf: packageURL,
            encoding: .utf8
        ).components(separatedBy: .newlines).first

        #expect(response.text.contains("scripted.reverse"))
        #expect(response.text.contains("stressed"))
        #expect(toolNames == [
            "feature.scaffold",
            "local.replace",
            "feature.validate",
            "feature.build",
            "feature.enable",
            "scripted.reverse"
        ])
        #expect(reverseOutput == "stressed")
        #expect(packageFirstLine == "// swift-tools-version: 6.3")
    }
}

private actor TestAgentRuntimeBackend: AgentRuntimeBackend {
    func createSession(
        id _: String,
        cwd _: String,
        systemPrompt _: String?,
        history _: [AgentRuntimeMessage],
        cacheKey _: String?,
        allowedToolNames _: Set<String>?,
        thinkingSelection _: AgentThinkingSelection?,
        preserveThinking _: Bool
    ) {}

    func createSessionIfNeeded(
        id _: String,
        cwd _: String,
        systemPrompt _: String?,
        history _: [AgentRuntimeMessage],
        cacheKey _: String?,
        allowedToolNames _: Set<String>?,
        thinkingSelection _: AgentThinkingSelection?,
        preserveThinking _: Bool
    ) {}

    func updateSessionOptions(
        id _: String,
        systemPrompt _: String?,
        allowedToolNames _: Set<String>?,
        thinkingSelection _: AgentThinkingSelection?,
        preserveThinking _: Bool
    ) {}

    func closeSession(id _: String) {}

    func shutdown() async {}

    func preloadModel(
        onEvent _: @escaping @Sendable (DirectAgentEvent) async -> Void
    ) async throws -> String {
        "test"
    }

    func activeToolDescriptors() async -> [DirectToolDescriptor] {
        []
    }

    func sendPrompt(
        sessionID _: String,
        prompt _: String,
        attachments _: [AgentRuntimeAttachment],
        onEvent _: @escaping @Sendable (DirectAgentEvent) async -> Void
    ) async throws -> DirectAgentResponse {
        DirectAgentResponse(text: "", stopReason: "end_turn", modelID: "test")
    }
}

private actor ScriptedFeatureAuthoringModelBackend: AgentRuntimeBackend {
    private struct Session {
        let cwd: URL
        var allowedToolNames: Set<String>?
    }

    private let toolExecutor: DirectToolExecutor
    private var sessions: [String: Session] = [:]

    init(toolExecutor: DirectToolExecutor) {
        self.toolExecutor = toolExecutor
    }

    func createSession(
        id: String,
        cwd: String,
        systemPrompt _: String?,
        history _: [AgentRuntimeMessage],
        cacheKey _: String?,
        allowedToolNames: Set<String>?,
        thinkingSelection _: AgentThinkingSelection?,
        preserveThinking _: Bool
    ) {
        sessions[id] = Session(
            cwd: URL(fileURLWithPath: cwd),
            allowedToolNames: allowedToolNames
        )
    }

    func createSessionIfNeeded(
        id: String,
        cwd: String,
        systemPrompt: String?,
        history: [AgentRuntimeMessage],
        cacheKey: String?,
        allowedToolNames: Set<String>?,
        thinkingSelection: AgentThinkingSelection?,
        preserveThinking: Bool
    ) {
        if sessions[id] == nil {
            createSession(
                id: id,
                cwd: cwd,
                systemPrompt: systemPrompt,
                history: history,
                cacheKey: cacheKey,
                allowedToolNames: allowedToolNames,
                thinkingSelection: thinkingSelection,
                preserveThinking: preserveThinking
            )
        }
    }

    func updateSessionOptions(
        id: String,
        systemPrompt _: String?,
        allowedToolNames: Set<String>?,
        thinkingSelection _: AgentThinkingSelection?,
        preserveThinking _: Bool
    ) {
        guard var session = sessions[id] else {
            return
        }
        session.allowedToolNames = allowedToolNames
        sessions[id] = session
    }

    func closeSession(id: String) {
        sessions[id] = nil
    }

    func shutdown() async {}

    func preloadModel(
        onEvent _: @escaping @Sendable (DirectAgentEvent) async -> Void
    ) async throws -> String {
        "scripted-model"
    }

    func activeToolDescriptors() async -> [DirectToolDescriptor] {
        await toolExecutor.descriptors()
    }

    func subAgentSnapshots() async -> [DirectSubAgentRuntime.AgentSnapshot] {
        []
    }

    func sendPrompt(
        sessionID: String,
        prompt: String,
        attachments _: [AgentRuntimeAttachment],
        onEvent: @escaping @Sendable (DirectAgentEvent) async -> Void
    ) async throws -> DirectAgentResponse {
        guard let session = sessions[sessionID] else {
            throw ScriptedFeatureAuthoringModelError.missingSession
        }
        guard prompt.localizedCaseInsensitiveContains("feature") else {
            throw ScriptedFeatureAuthoringModelError.unexpectedPrompt(prompt)
        }

        func callTool(
            id: Int,
            _ name: String,
            arguments: [String: Any]
        ) async throws -> String {
            let toolCall = DirectAgentToolCall(
                id: "scripted-feature-tool-\(id)",
                name: name,
                argumentsObject: arguments,
                argumentsJSON: try Self.jsonString(from: arguments)
            )
            await onEvent(.toolCallStarted(toolCall))
            let result = await toolExecutor.execute(
                sessionID: sessionID,
                toolCall: toolCall,
                workingDirectory: session.cwd,
                allowedToolNames: session.allowedToolNames
            )
            await onEvent(.toolCallCompleted(toolCall, result))
            if result.output.hasPrefix("Tool error:") {
                throw ScriptedFeatureAuthoringModelError.toolFailed(name, result.output)
            }
            return result.output
        }

        let scaffoldOutput = try await callTool(
            id: 1,
            "feature.scaffold",
            arguments: [
                "id": "scripted-reverse",
                "toolName": "scripted.reverse"
            ]
        )
        let scaffold = try JSONDecoder().decode(
            SwiftFeatureScaffoldReport.self,
            from: Data(scaffoldOutput.utf8)
        )
        _ = try await callTool(
            id: 2,
            "local.replace",
            arguments: [
                "path": scaffold.sourcePath,
                "oldString": #"return input.text ?? """#,
                "newString": #"return String((input.text ?? "").reversed())"#
            ]
        )

        let validationOutput = try await callTool(
            id: 3,
            "feature.validate",
            arguments: [
                "id": "scripted-reverse"
            ]
        )
        let validation = try JSONDecoder().decode(
            SwiftFeatureValidationReport.self,
            from: Data(validationOutput.utf8)
        )
        guard validation.ok else {
            throw ScriptedFeatureAuthoringModelError.validationFailed(validation.errors)
        }

        let buildOutput = try await callTool(
            id: 4,
            "feature.build",
            arguments: [
                "id": "scripted-reverse"
            ]
        )
        let build = try JSONDecoder().decode(
            SwiftFeatureBuildReport.self,
            from: Data(buildOutput.utf8)
        )
        guard build.ok else {
            throw ScriptedFeatureAuthoringModelError.buildFailed(build.stderr)
        }

        _ = try await callTool(
            id: 5,
            "feature.enable",
            arguments: [
                "id": "scripted-reverse"
            ]
        )
        let reverseOutput = try await callTool(
            id: 6,
            "scripted.reverse",
            arguments: [
                "text": "desserts"
            ]
        )
        guard reverseOutput == "stressed" else {
            throw ScriptedFeatureAuthoringModelError.unexpectedToolOutput(reverseOutput)
        }

        return DirectAgentResponse(
            text: "Generated feature scripted.reverse returned \(reverseOutput).",
            stopReason: "end_turn",
            modelID: "scripted-model"
        )
    }

    private static func jsonString(from object: [String: Any]) throws -> String {
        let data = try JSONValue(jsonObject: object).jsonData(
            outputFormatting: [.sortedKeys, .withoutEscapingSlashes]
        )
        return String(data: data, encoding: .utf8) ?? "{}"
    }
}

private enum ScriptedFeatureAuthoringModelError: LocalizedError {
    case missingSession
    case unexpectedPrompt(String)
    case toolFailed(String, String)
    case validationFailed([String])
    case buildFailed(String)
    case unexpectedToolOutput(String)

    var errorDescription: String? {
        switch self {
        case .missingSession:
            return "The scripted feature authoring model has no active session."
        case let .unexpectedPrompt(prompt):
            return "The scripted feature authoring model received an unexpected prompt: \(prompt)"
        case let .toolFailed(name, output):
            return "Tool \(name) failed during scripted feature authoring: \(output)"
        case let .validationFailed(errors):
            return "Generated feature validation failed: \(errors.joined(separator: "\n"))"
        case let .buildFailed(stderr):
            return "Generated feature build failed: \(stderr)"
        case let .unexpectedToolOutput(output):
            return "Generated feature returned unexpected output: \(output)"
        }
    }
}

private actor DirectAgentEventRecorder {
    private var startedNames: [String] = []
    private var completedOutputsByName: [String: String] = [:]

    func record(_ event: DirectAgentEvent) {
        switch event {
        case let .toolCallStarted(toolCall):
            startedNames.append(toolCall.name)
        case let .toolCallCompleted(toolCall, result):
            completedOutputsByName[toolCall.name] = result.output
        default:
            break
        }
    }

    func startedToolNames() -> [String] {
        startedNames
    }

    func completedOutput(for toolName: String) -> String? {
        completedOutputsByName[toolName]
    }
}
